#version 450
#include "../shared_shader_fragments/el_number_to_lin_mem_idx.comph"
#include "../shared_shader_fragments/tensor_a_definition.comph"

layout(local_size_x = 1) in;

layout(set = 0, binding = 5) buffer OutputBuffer {
    float[] output_buffer;
};


void main() {
    uint element_number = gl_GlobalInvocationID.x; // 0 1 2 3
    uint linear_offset_a = get_linear_offset_a(element_number);

    output_buffer[element_number] = ten_a[linear_offset_a];
}


